name: Rubbergoddess

on:
  push:
    branches: [ master ]
    paths:
    - "**/*.py"
    - "**/*.yml"
  pull_request:
    paths:
    - "**/*.py"
    - "**/*.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check the code for errors
      run: |
        flake8 . --count --select=BLK,E9,F70,F82 --statistics

    - name: Check the code for non-critical errors
      run: |
        flake8 . --exit-zero
