name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: .
          config: .flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
